---
baseurl: "/"
theme: stage
metaDataFormat: yaml
params:
  title: Stage
  subtitle: A Hugo theme for musicians and creative types.
  coverimage: "/images/stage.jpg"
  social:
    facebook: http://facebook.com/
    soundcloud: http://soundcloud.com/
    reverbnation: http://reverbnation.com/
    contact: "/"
  authors:
    stage:
      name: Stage
      description: Enter an artist description here.
      image: "/images/avatar.png"
      link: "/"
  navbar:
    blog: "/post/"
    bio: "/"
    music: "/album/"
    events: "/event/"
    media: "/media/"
  fonts: Lato:300,500,700
  maps: 'true'
